{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.services.openstack.keystone;
  commonCfg = config.services.openstack.common;
in

{
  options.services.openstack.keystone = {
    enable = mkEnableOption "OpenStack Keystone identity service";

    package = mkPackageOption pkgs "openstack-keystone" { };

    database = {
      name = mkOption {
        type = types.str;
        default = "keystone";
        description = "Keystone database name";
      };

      user = mkOption {
        type = types.str;
        default = "keystone";
        description = "Keystone database user";
      };

      password = mkOption {
        type = types.str;
        description = "Keystone database user's password";
      };

      address = mkOption {
        type = types.str;
        default = "localhost";
        description = "Keystone database address";
      };
    };

    extraSettings = mkOption {
      type = types.attrs;
      default = { };
      description = "Keystone configuration sections";
      example = {
        DEFAULT = {
          debug = true;
          use_stderr = true;
        };
      };
    };
  };

  config = mkIf cfg.enable {
    # Configure Database
    services.mysql = {
      initialScript = pkgs.writeText "init-keystone.sql" ''
        GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'${cfg.database.address}' IDENTIFIED BY '${cfg.database.password}';
      '';
      # Add keystone as required database
      ensureDatabases = [ cfg.database.name ];
      # Configure keystone user and permissions for Keystone database
      ensureUsers = [
        {
          name = cfg.database.user;
          ensurePermissions = {
            "${cfg.database.name}.*" = "ALL PRIVILEGES";
          };
        }
      ];
    };

    # Create user and group for keystone to run
    users.extraUsers.keystone = {
      group = cfg.database.user;
      isSystemUser = true;
    };
    users.groups.keystone = {
      name = cfg.database.user;
      members = [ cfg.database.user ];
    };

    # Some componant (e.g. keystone-wsgi-public) expect the config file at the default location
    # TODO(vinetos): Test if it is still true, We might pass all the config using CLI parameters (--config-file) ?
    environment.etc."keystone/keystone.conf".source =
      let
        keystoneConfig = {
          database = {
            connection = "mysql+pymysql://${cfg.database.user}:${cfg.database.password}@${cfg.database.address}/${cfg.database.name}";
          };
          token = {
            provider = "fernet";
          };
        };
      in
      (pkgs.formats.ini { }).generate "keystone.conf" (keystoneConfig // cfg.extraSettings);

    # oneshot systemd to bootstrap keystone at the very first start
    systemd.services.keystone-bootstrap = {
      description = "Bootstrap OpenStack Keystone";
      wantedBy = [ "keystone.service" ];
      before = [ "keystone.service" ];
      after = [ "mysql.service" ];

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        User = cfg.database.user;
        Group = cfg.database.user;
      };

      script = ''
        # Populate the Identity service database
        ${pkgs.keystone}/bin/keystone-manage db_sync # Ca n'existe pas, voir pour le package ??

        # Initialize Fernet key repositories
        ${pkgs.keystone}/bin/keystone-manage fernet_setup --keystone-user ${cfg.database.user} --keystone-group ${cfg.database.user}
        ${pkgs.keystone}/bin/keystone-manage credential_setup --keystone-user ${cfg.database.user} --keystone-group ${cfg.database.user}

        # Bootstrap the Identity service
        ${pkgs.keystone}/bin/keystone-manage bootstrap --bootstrap-password ADMIN_PASS --bootstrap-admin-url http://controller:5000/v3/ --bootstrap-internal-url http://controller:5000/v3/ --bootstrap-public-url http://controller:5000/v3/ --bootstrap-region-id RegionOne
      '';

      unitConfig = {
        ConditionPathExists = "!/var/lib/keystone/.db-synced";
      };

      postStart = ''
        touch /var/lib/keystone/.db-synced
      '';
    };

    # # Service implementation
    # systemd.services.keystone = {
    #   description = "OpenStack Keystone Identity Service";
    #   after = [
    #     "network.target"
    #     "postgresql.service"
    #   ];
    #   wantedBy = [ "multi-user.target" ];

    #   serviceConfig = {
    #     Type = "notify";
    #     User = "keystone";
    #     Group = "keystone";
    #     ExecStart = "${cfg.package}/bin/keystone-wsgi-public";
    #     # More config...
    #   };
    # };

    # environment.etc."keystone/keystone.conf".text = ''
    #   [DEFAULT]
    #   # Configuration generated by NixOS

    #   [database]
    #   connection = postgresql://${cfg.database.user}@${cfg.database.host}/${cfg.database.name}

    #   # More configuration...
    # '';
  };
}
